#!/usr/bin/bash
pushd $1
VER_MAJ=1
VER_MIN=0
VER_BUILD=$(date +%d%m%y)
VER_REV=$(date +%S)e0
echo "#pragma once" > $2
echo "// File generated by tools/genosver.sh" >> $2
echo "#define OS_VER_MAJOR $VER_MAJ" >> $2
echo "#define OS_VER_MINOR $VER_MIN" >> $2
echo "#define OS_VER_BUILD $VER_BUILD" >> $2
echo "#define OS_VER_REV (int)($VER_REV)" >> $2
popd