#pragma once
typedef enum {
    OS_EXIT,
    OS_KILL,
    OS_SPAWN,
    OS_CONWRITE,
    OS_YIELD,
    OS_GETPID,
    OS_WAIT,
    OS_SBRK,
    OS_SETFSBASE,
    OS_OPEN,
    OS_CLOSE,
    OS_READ,
    OS_WRITE,
    OS_SEEK,
    OS_GETCLOCK,
    OS_CHDIR,
    OS_GETCWD,
    OS_STAT,
    OS_FSTAT,
    OS_GETDIRENT,
    OS_UNAME,
    OS_UMASK,
    OS_IOCTL,
    OS_CRPIPE,
    OS_FORK,
    OS_EXECVE,
    OS_DUP,
    OS_DUP2,
    OS_GETPPID,
    OS_ACCESS
} KiSyscallIdx;